services:
  - name: eureka-microserv
    type: web
    env: docker
    dockerfilePath: ./eureka/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: "8761"
    healthCheckPath: /actuator/health
    autoDeploy: true

  - name: gateway-microserv
    type: web
    env: docker
    dockerfilePath: ./gateway/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: "8080"
    dependencies:
      - eureka-microserv
    autoDeploy: true

  - name: producto1-microserv
    type: web
    env: docker
    dockerfilePath: ./producto1/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: "8001"
    dependencies:
      - eureka-microserv
    autoDeploy: true

  - name: producto2-microserv
    type: web
    env: docker
    dockerfilePath: ./producto2/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: "8002"
    dependencies:
      - eureka-microserv
    autoDeploy: true

  - name: user-microserv
    type: web
    env: docker
    dockerfilePath: ./usuario/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: "8003"
    dependencies:
      - eureka-microserv
    autoDeploy: true
