spring:
  application:
    name: usuario
eureka:
  client:
    service-url:
      defaultZone: http://eureka-microserv:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
server:
  port: 8003

user:
  json:
    path: /usuario/data/data.json
